version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'saturday'
    versioning-strategy: 'increase'
    pull-request-branch-name:
      separator: '-'
    ignore:
      - dependency-name: '@salesforce/dev-scripts'
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
    groups:
      dependencies:
        patterns:
          - '*'
